### ISSUE TITLE
没有mirflickr25k-iall.mat文件

### ISSUE THREAD

**Issue by liangjxiong** [penghu-cs/UCCH#16]
运行 python UCCH.py --data_name mirflickr25k --bit 128 --alpha 0.7 --num_hiden_layers 3 2 --margin 0.2 --max_epochs 20 --train_batch_size 256 --shift 0.1 --lr 0.0001 --optimizer Adam --warmup_epoch 5 --pretrain -a vgg11 命令，报 FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = './data/MIRFLICKR25K/mirflickr25k-iall.mat', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0) 错误。
请问可以提供mirflickr25k-iall.mat文件的下载链接吗？谢谢！

**Comment by penghu-cs** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    下载链接如下：MIRFLICKR25K:
link: https://pan.baidu.com/s/1o5jSliFjAezBavyBOiJxew
password: 8dub祝好，鹏
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                penghu.ml
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年01月25日 10:48
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [penghu-cs/UCCH] 没有mirflickr25k-iall.mat文件 (Issue #16)
        
      
    
  
  
运行 python UCCH.py --data_name mirflickr25k --bit 128 --alpha 0.7 --num_hiden_layers 3 2 --margin 0.2 --max_epochs 20 --train_batch_size 256 --shift 0.1 --lr 0.0001 --optimizer Adam --warmup_epoch 5 --pretrain -a vgg11 命令，报 FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = './data/MIRFLICKR25K/mirflickr25k-iall.mat', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0) 错误。
请问可以提供mirflickr25k-iall.mat文件的下载链接吗？谢谢！

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
