### ISSUE TITLE
Some questions about the techniques in paper

### ISSUE THREAD

**Issue by nwod-edispu** [penghu-cs/UCCH#18]
Thanks for your great work!

I have some questions about the techniques presented in paper. In the contrastive function in eq 4, you aim to align the real-valued vector $h_i^x$ and $h_i^y$ to the binary hash code $k_i$. In this training sceme, the final representation of $h_i^{\*}$ will have a high similarity score  to $k_i$. But the final goal of hashing is to make $sign(h_i^{\*})$ similar to $k_i$. I think there is a gap between these two kind of objective and the contrastive loss could not enforce the samples to approximate the hash codes but just enforce them to have high similarity score.

Looking forward to your reply!

**Comment by penghu-cs** [comment]
Thank you for your interest in our work. You raise an important point. While it's true that the contrastive loss aims to maximize the similarity between $h_i^\*$ and $k_i$, this alignment is indeed a step toward approximating the hash codes. Since $k_i$ is binarized, a higher similarity between $h_i^\*$ and $k_i$ implies that $h_i^\*$ is closer to the hash code. As $h_i^\*$ approximates the hash codes, it naturally becomes more similar to $k_i$, including its sign (i.e., $sign ( h_i^\* ) $). We hope this clarification addresses your concern. Thank you again for your interest.

**Comment by kuaile258890** [comment]
> Thank you for your interest in our work. You raise an important point. While it's true that the contrastive loss aims to maximize the similarity between hi∗ and ki, this alignment is indeed a step toward approximating the hash codes. Since ki is binarized, a higher similarity between hi∗ and ki implies that hi∗ is closer to the hash code. As hi∗ approximates the hash codes, it naturally becomes more similar to ki, including its sign (i.e., sign(hi∗)). We hope this clarification addresses your concern. Thank you again for your interest.

Hi. I agree with your statement. Due to the non-differentiability of the sign function, a series of cutting-edge works, including yours, can only approximate binary values with continuous values. Although this approach can indeed achieve very good results, I think there is essentially a mismatch in the training task, that is, we hope that $sign(h^{\*}_i)$ is similar to $k_i$ rather than $h^\*_i$. Meanwhile, in the training of UCCH, it is found that because the feature of text is represented by the BoW vector, the real value output after passing through the MLP and then being normalized is very small (when the number of bits increases, such as 128 bits, it may be less than 0.01), which actually leads to a very large quantization loss. However, UCCH has taken a very smart approach where one side of the dot product ($k_i$) is binary values stored similar to the MoCo queue, which is somewhat like the previous works JDSH and DGCPN, which also adopted the practice of dot product between real values and binary values, thereby alleviating the mismatch issue between training tasks. Of course, I still believe that the huge quantization loss brought by the text part (the difference between 0.01 and 1) limits the model performance, which may be a direction for future improvement.

**Comment by penghu-cs** [comment]
Thank you for your thoughtful and detailed analysis.  You’ve highlighted some key challenges in the field, particularly the non-differentiability of the sign function and the mismatch in training tasks.  Your observations about the UCCH training and the quantization loss are particularly insightful.  Indeed, the approach taken by UCCH does help alleviate some of these issues.  However, as you rightly pointed out, some quantization losses could be limiting the model’s performance.  This is certainly an area that warrants further exploration and improvement.  Your input is greatly appreciated and will undoubtedly contribute to the ongoing efforts in our community.
